In [1]:
import cv2
import numpy as np

**Load/Read image**

In [2]:
img = cv2.imread(r'C:\Users\sahur\Downloads\Modi_image.jpg',1)


In [3]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [4]:
img.shape

(1358, 1500, 3)

**Display the image**

In [18]:
img = cv2.imread(r'C:\Users\sahur\Downloads\Modi_image.jpg')
cv2.imshow('PM',img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

**Save image**

In [6]:
cv2.imwrite('pm_b_w.jpg',img)

True

**Resize Image**

In [19]:
img = cv2.imread(r'C:\Users\sahur\Downloads\Modi_image.jpg')

resized_image = cv2.resize(img,(500,500))

gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

cv2.imshow('Modi Image',gray)

cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
img.shape[0]*0.5

679.0

In [9]:
img.shape[1]*0.5

750.0

**Face Detection using HAAR Cascade Classifier**

In [20]:
face_classifier = cv2.CascadeClassifier(r'C:\Users\sahur\Downloads\haarcascade_frontalface_default.xml')

# load our image then convert it to grayscale
image = cv2.imread(r'C:\Users\sahur\Downloads\Modi_image.jpg')
image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

#Tuning Cascade Classifier - detectMUltiScale (input image,**Scale Factor**,**Min Neighbours**)
faces = face_classifier.detectMultiScale(gray,1.05,5)

In [21]:
print(faces)

[[205  79 217 217]]


In [22]:
if len(faces) == 0:
    print('No faces found')

# Draw rectangles over each detected face
for (x, y, w, h) in faces:
    cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 100), 1)

cv2.imshow('Face Detection', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


**Face & Eye Detection using HAAR Cascade Classifier in Image**

In [23]:
face_classifier = cv2.CascadeClassifier(r'C:\Users\sahur\Downloads\haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier(r'C:\Users\sahur\Downloads\haarcascade_eye.xml')

img = cv2.imread(r'C:\Users\sahur\Downloads\Modi_image.jpg')
resized_image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray,1.3,5)


if len(faces)==0:
    print('No faces Found')

for (x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h,x:x+w]
    roi_color = resized_image[y:y+h,x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

cv2.imshow('img',resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

**Capture a video**

In [24]:
import cv2
video = cv2.VideoCapture(0) # 0--webcam
while True:
    check,frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video',gray)
    if cv2.waitKey(1) == ord('q'):
        break

video.release()
cv2.destroyAllWindows()

**Face & Eye Detection using HAAR Cascade Classifiers**

In [25]:
face_cascade = cv2.CascadeClassifier(r'C:\Users\sahur\Downloads\haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(r'C:\Users\sahur\Downloads\haarcascade_eye.xml')

def detect(gray,frame):
    faces = face_cascade.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h,x:x+w]
        roi_color = frame[y:y+h,x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray,1.1,3)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    return frame

video = cv2.VideoCapture(0)

while True:
    check,frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas = detect(gray,frame)
    cv2.imshow('Video',canvas)
    if cv2.waitKey(1)==ord('q'):
        break

video.release()
cv2.destroyAllWindows()  

**Pedistrian Detection**

In [26]:
import cv2 
# Create our body Classifier
body_classifier = cv2.CascadeClassifier(r'C:\Users\sahur\Downloads\haarcascade_fullbody.xml')

# Initiate video capture for video file
cap = cv2.VideoCapture(r'C:\Users\sahur\Downloads\walking.avi')


while cap.isOpened():
    # Read first frame
    check,frame = cap.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    # pass frame to our body classifier
    bodies = body_classifier.detectMultiScale(gray,1.2,3)
    # Extract bounding boxes for any bodies identified
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        cv2.imshow('Pedestrians',frame)

    if cv2.waitKey(1)==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

**Car Detection**

In [27]:
import time

# Create our body classifier
car_classifier = cv2.CascadeClassifier(r'C:\Users\sahur\Downloads\haarcascade_car.xml')

# Initiate video capture for video fileq
cap = cv2.VideoCapture(r'C:\Users\sahur\Downloads\cars.avi')


while cap.isOpened():
    time.sleep(.05)
    # Read first frame
    check,frame = cap.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        # pass frame to our car classifier
    cars = car_classifier.detectMultiScale(gray,1.4,2)

    # Extract bounding boxes for any bodies identified
    for (x,y,w,h) in cars:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        cv2.imshow('Cars',frame)
    if cv2.waitKey(1)==ord('q'):
        break

cap.release()
cv2.destroyAllWindows()